[env]
EMCC_CFLAGS = "-s EXIT_RUNTIME -s ASYNCIFY -s USE_GLFW=3 -DPLATFORM_WEB -sGL_ENABLE_GET_PROC_ADDRESS -DGRAPHICS_API_OPENGL_ES2 -sEXPORTED_FUNCTIONS=_main,_on_resize -sEXPORTED_RUNTIME_METHODS=ccall,cwrap"
