on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-examples-linux:
    runs-on: ubuntu-latest
    env:
      ROC_VERSION: nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install Build Essentials
        run: sudo apt install build-essential git

      - name: Install Rust and Cargo
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install ROC
        run: |
          # Install ROC
          curl -fOL https://github.com/roc-lang/roc/releases/download/${ROC_VERSION}/roc_nightly-linux_x86_64-latest.tar.gz
          mv $(ls | grep "roc_nightly.*tar\.gz") roc_nightly.tar.gz
          tar -xzf roc_nightly.tar.gz
          rm roc_nightly.tar.gz
          mv roc_nightly* roc_nightly

      - name: Check ROC version
        run: ./roc_nightly/roc version

      - name: Run all tests
        run: ROC=./roc_nightly/roc ./ci/all_tests.sh

  test-examples-macos:
    runs-on: macos-latest
    env:
      ROC_VERSION: nightly
      DYLD_LIBRARY_PATH: /usr/local/opt/zstd/lib
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Essentials
        run: brew install automake autoconf libtool

      - name: Install zstd
        run: |
          brew install zstd
          brew link zstd

          # Create symlink in /usr/local/lib
          sudo mkdir -p /usr/local/lib
          sudo ln -sf $(brew --prefix zstd)/lib/libzstd.* /usr/local/lib/

      - name: Install Rust and Cargo
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install ROC
        run: |
          # Install ROC
          curl -fOL https://github.com/roc-lang/roc/releases/download/${ROC_VERSION}/roc_nightly-macos_x86_64-latest.tar.gz
          mv $(ls | grep "roc_nightly.*tar\.gz") roc_nightly.tar.gz
          tar -xzf roc_nightly.tar.gz
          rm roc_nightly.tar.gz
          mv roc_nightly* roc_nightly

      - name: Check ROC version
        run: ./roc_nightly/roc version

      - name: Run all tests
        run: ROC=./roc_nightly/roc ./ci/all_tests.sh
